### ISSUE TITLE
question about zcu102

### ISSUE THREAD

**Issue by TKNopro** [gkrislara/Image-super-resolution-FPGA#1]
Hello, can you take the liberty to ask you to release the hardware configuration about zcu102. Thank you

**Comment by gkrislara** [comment]
I am not in a position to release the hardware configuration for now, since I have moved to latest version and the design is archived.
This hardware design is similar to that of the base design given by xilinx follow the installation procedure and writing image to sdcard
([link](https://www.xilinx.com/html_docs/vitis_ai/1_3/installation.html#qoi1603967292432))
